services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: student_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: student_db
    depends_on:
      - db

# YE VALA HISSA ZARURI HAI (Aapki file mein ye missing tha)
volumes:
  mysql_data: