apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: techfaiyaz5/student-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: LoadBalancer  # <--- NodePort se badal kar LoadBalancer kar diya
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80         # Bahar se access ke liye port
      targetPort: 8080 # Tumhari Flask app ka port (Logs ke hisaab se)
      nodePort: 30001  # Static port browser ke liye