apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: techfaiyaz5/student-app:latest # Tumhari Docker Hub image
        imagePullPolicy: Always # Har baar fresh image pull karega
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"  # 0.1 CPU core (Base line)
          limits:
            cpu: "200m"  # Max limit jiske basis pe % niklega
        env:
        - name: DB_HOST
          value: "db-service"  # <--- Ye tumhare MySQL service ka naam hai
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"    # Ensure karo ye tumhare MySQL setup wala hi password hai
        - name: DB_NAME
          value: "student_db"
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: LoadBalancer 
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80         # Internal port
      targetPort: 8080 # App ka port
      nodePort: 30001  # <--- Ye tumhara Universal Fixed Port hai